In [1]:
# Function to compute even parity bit
def compute_even_parity(data):
# Sum the data bits and take modulo 2.
# If sum is odd, parity bit is 1 (to make total even); if even, parity bit is 0.
  return sum(data) % 2
# Original data bits (example)
data = [1, 0, 1, 0, 1, 1, 0, 0]
parity_bit = compute_even_parity(data)
print("Original Data: ", data)
print("Computed Parity Bit (Even):", parity_bit)
# Transmitted data: append parity bit to the data array
transmitted_data = data + [parity_bit]
print("\nTransmitted Data (Data + Parity):", transmitted_data)

Original Data:  [1, 0, 1, 0, 1, 1, 0, 0]
Computed Parity Bit (Even): 0

Transmitted Data (Data + Parity): [1, 0, 1, 0, 1, 1, 0, 0, 0]


In [ ]:
def compute_even_parity(data):
    # Sum the data bits and take modulo 2.
    # If sum is odd, parity bit is 1 (to make total even); if even, parity bit is 0.
    return sum(data) % 2

test_cases = [
    [1, 0, 1, 0, 1, 1, 0, 0],  # Example from the original code
    [1, 1, 1, 1, 1, 1, 1],      # All ones
    [0, 0, 0, 0, 0, 0],         # All zeros
    [1, 0, 1, 1, 0, 0, 1],      # Mixed bits
]

for data in test_cases:
    parity_bit = compute_even_parity(data)
    transmitted_data = data + [parity_bit]
    
    print("Original Data: ", data)
    print("Computed Parity Bit (Even):", parity_bit)
    print("Transmitted Data (Data + Parity):", transmitted_data)
    


Original Data:  [1, 0, 1, 0, 1, 1, 0, 0]
Computed Parity Bit (Even): 0
Transmitted Data (Data + Parity): [1, 0, 1, 0, 1, 1, 0, 0, 0]
Original Data:  [1, 1, 1, 1, 1, 1, 1]
Computed Parity Bit (Even): 1
Transmitted Data (Data + Parity): [1, 1, 1, 1, 1, 1, 1, 1]
Original Data:  [0, 0, 0, 0, 0, 0]
Computed Parity Bit (Even): 0
Transmitted Data (Data + Parity): [0, 0, 0, 0, 0, 0, 0]
Original Data:  [1, 0, 1, 1, 0, 0, 1]
Computed Parity Bit (Even): 0
Transmitted Data (Data + Parity): [1, 0, 1, 1, 0, 0, 1, 0]


In [3]:
# Simulate an error: flip a bit in the transmitted data
# For example, flip the bit at index 3 (0-indexed)
error_index = 3
data_with_error = transmitted_data.copy()
data_with_error[error_index] = 1 - data_with_error[error_index]
print("\nData with an Error Introduced at index", error_index, ":",
data_with_error)
# At the receiver, perform the parity check.
# For even parity, the sum of all bits should be even.
if sum(data_with_error) % 2 == 0:
  print("\nNo error detected (Parity Check Passed)")
else:
  print("\nError detected (Parity Check Failed)")


Data with an Error Introduced at index 3 : [1, 0, 1, 0, 0, 0, 1, 0]

Error detected (Parity Check Failed)


In [7]:
import numpy as np

def compute_parity(mat):
    # Returns (row_parity, col_parity) for even parity
    return np.sum(mat, axis=1) % 2, np.sum(mat, axis=0) % 2

# Create a 4x4 data matrix
data = np.array([
    [1, 0, 1, 1],
    [0, 1, 0, 0],
    [1, 1, 1, 0],
    [0, 0, 1, 1]
])

print("Original Data:\n", data)

# Compute original parity bits
row_par, col_par = compute_parity(data)
print("Row Parity:", row_par)
print("Column Parity:", col_par)

# Introduce an error at position (2, 1)
data_err = data.copy()
data_err[2, 1] = 1 - data_err[2, 1]
print("\nData with error at (2, 1):\n", data_err)

# Recompute parity bits after error
new_row_par, new_col_par = compute_parity(data_err)
print("New Row Parity:", new_row_par)
print("New Column Parity:", new_col_par)

# Detect and correct the error
err_row = np.where(new_row_par != row_par)[0]
err_col = np.where(new_col_par != col_par)[0]

if err_row.size == 1 and err_col.size == 1:
    error_location = (err_row[0], err_col[0])
    print("\nError detected at:", error_location)
    
    # Correct the error by flipping the bit back
    data_err[error_location] = 1 - data_err[error_location]
    print("Corrected Data:\n", data_err)
else:
    print("No single-bit error detected or multiple errors occurred.")


Original Data:
 [[1 0 1 1]
 [0 1 0 0]
 [1 1 1 0]
 [0 0 1 1]]
Row Parity: [1 1 1 0]
Column Parity: [0 0 1 0]

Data with error at (2, 1):
 [[1 0 1 1]
 [0 1 0 0]
 [1 0 1 0]
 [0 0 1 1]]
New Row Parity: [1 1 0 0]
New Column Parity: [0 1 1 0]

Error detected at: (np.int64(2), np.int64(1))
Corrected Data:
 [[1 0 1 1]
 [0 1 0 0]
 [1 1 1 0]
 [0 0 1 1]]


In [ ]:
def ones_complement_sum(a, b, bit_size=16):
 """Perform one's complement addition of two numbers."""
 result = a + b
 if result >= (1 << bit_size): # If there's an overflow
  result = (result + 1) & ((1 << bit_size) - 1) # Wrap around carry
 return result
def calculate_checksum(data, bit_size=16):
 """Compute one's complement checksum for a list of integers."""
 checksum = 0
 for word in data:
  checksum = ones_complement_sum(checksum, word, bit_size)
  return ~checksum & ((1 << bit_size) - 1) # One's complement
def verify_checksum(data, received_checksum, bit_size=16):
 """Verify the checksum by adding it to the computed sum."""
 total = 0
 for word in data:
  total = ones_complement_sum(total, word, bit_size)
  total = ones_complement_sum(total, received_checksum, bit_size)
  return total == (1 << bit_size) - 1 # Valid if all bits are 1
# Example Usage
 data = [0b1010101010101010, 0b1100110011001100, 0b1111000011110000] # Example 16-bit words
 checksum = calculate_checksum(data)
 print(f"Calculated Checksum: {bin(checksum)}")
# Verification
 is_valid = verify_checksum(data, checksum)
 print("Checksum is valid" if is_valid else "Checksum is invalid")

In [9]:
import random
import matplotlib.pyplot as plt
import numpy as np

def simulate_slotted_aloha(n_nodes, p, n_slots):
    successes = 0
    for _ in range(n_slots):
        # Each node transmits with probability p in a slot
        transmissions = sum(1 for _ in range(n_nodes) if random.random() < p)
        if transmissions == 1:  # A successful transmission occurs when exactly one node transmits
            successes += 1
    efficiency = successes / n_slots
    return efficiency

n_nodes = 50
ps = np.linspace(0, 1, 50)  # Transmission probability values
efficiencies = [simulate_slotted_aloha(n_nodes, p, 10000) for p in ps]

plt.plot(ps, efficiencies, marker='o')
plt.xlabel('Transmission Probability')
plt.ylabel('Efficiency')
plt.title('Slotted ALOHA Efficiency Simulation')
plt.grid()
plt.show()



ModuleNotFoundError: No module named 'matplotlib'